runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT app:app


runtime_config:
  python_version: 37
 
 env_variables:
  SECRET_KEY:  'caf3cc4546725599c99158599d443fc815bd137b73b0b69bc804f3ba483aeaa224c75a2b3fc1f35eccfdfef6cdd01858450435ef6daed0c49bf01fbe1e7b3b79'
  DB: "mysql://rkpmtiv6bbvm81e5:yz1mq64u3h1sab93@nwhazdrp7hdpd4a4.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ztqqdjf98kpnzn4n"
  HOST: "nwhazdrp7hdpd4a4.cbetxkdyhwsb.us-east-1.rds.amazonaws.com"
  USER: "rkpmtiv6bbvm81e5"
  PASSWORD: "yz1mq64u3h1sab93"
  DATABASE: "ztqqdjf98kpnzn4n"